// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  nav_link: dynamic(() => import("./NavLink")),
  rich_text: dynamic(() => import("./RichText")),
};
